CREATE TABLE IF NOT EXISTS favourites(
    id INT PRIMARY KEY, 
    CityName VARCHAR(85) NOT NULL,
    Longitude DECIMAL (10,10) NOT NULL,
    Latitude DECIMAL (10,10) NOT NULL,
    AddDate DATE DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS Searchhistory(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    City VARCHAR(85) NOT NULL,
    LongitudeSearch DECIMAL (10,10) NOT NULL,
    LatitudeSearch DECIMAL (10,10) NOT NULL,
    Dateadded DATE DEFAULT CURRENT_DATE
);